# Generated by Django 6.0.2 on 2026-02-24 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guns',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('serial_no', models.CharField(blank=True, max_length=250, null=True)),
                ('make', models.CharField(blank=True, max_length=250, null=True)),
                ('kind', models.CharField(blank=True, max_length=250, null=True)),
                ('caliber', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
            ],
            bases=('quickstart.basemodel',),
        ),
        migrations.CreateModel(
            name='TransferredFirearms',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('no', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('to', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
            ],
            bases=('quickstart.basemodel',),
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('unit', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_unit', models.CharField(blank=True, max_length=250, null=True)),
            ],
            bases=('quickstart.basemodel',),
        ),
        migrations.CreateModel(
            name='OnStocks',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('disposition', models.CharField(blank=True, max_length=250, null=True)),
                ('type_of_issuance', models.CharField(blank=True, max_length=250, null=True)),
                ('validated', models.CharField(blank=True, max_length=250, null=True)),
                ('gun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.guns')),
            ],
            bases=('quickstart.basemodel',),
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('rank', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('station', models.CharField(blank=True, max_length=250, null=True)),
                ('issued_unit', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.units')),
            ],
            bases=('quickstart.basemodel',),
        ),
    ]
