# Generated by Django 6.0.2 on 2026-02-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_guns_transferredfirearms_units_onstocks_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onstocks',
            name='validated',
        ),
        migrations.AddField(
            model_name='guns',
            name='validated',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
