# Generated by Django 6.0.2 on 2026-02-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_remove_onstocks_validated_guns_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
