# Generated by Django 6.0.2 on 2026-02-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_persons_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='persons',
            name='middle_name',
        ),
    ]
