# Generated by Django 6.0.2 on 2026-02-24 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_rename_first_name_persons_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='gun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.guns'),
        ),
    ]
