# Generated by Django 6.0.2 on 2026-02-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_guns_faid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guns',
            name='model',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
