# Generated by Django 6.0.2 on 2026-03-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_guns_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='sub_unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
