# Generated by Django 6.0.2 on 2026-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_alter_persons_unit_persons_sub_unit_delete_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='person_attachments/'),
        ),
    ]
