# Generated by Django 6.0.2 on 2026-03-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_persons_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persons',
            old_name='attachment',
            new_name='par',
        ),
    ]
