# Generated by Django 6.0.2 on 2026-03-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_rename_attachment_persons_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='par',
        ),
        migrations.CreateModel(
            name='Par',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('img', models.FileField(blank=True, null=True, upload_to='person_attachments/')),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
                ('Persons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.persons')),
            ],
            bases=('quickstart.basemodel',),
        ),
        migrations.CreateModel(
            name='TurnIn',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('img', models.FileField(blank=True, null=True, upload_to='person_attachments/')),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
                ('on_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.onstocks')),
            ],
            bases=('quickstart.basemodel',),
        ),
        migrations.DeleteModel(
            name='TransferredFirearms',
        ),
    ]
