# Generated by Django 6.0.2 on 2026-03-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_remove_persons_par_par_turnin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pars',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('img', models.FileField(blank=True, null=True, upload_to='person_attachments/')),
                ('date', models.CharField(blank=True, max_length=250, null=True)),
            ],
            bases=('quickstart.basemodel',),
        ),
        migrations.RemoveField(
            model_name='turnin',
            name='on_stock',
        ),
        migrations.AddField(
            model_name='onstocks',
            name='turn_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.turnin'),
        ),
        migrations.AddField(
            model_name='persons',
            name='par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.pars'),
        ),
        migrations.DeleteModel(
            name='Par',
        ),
    ]
