# Generated by Django 6.0.2 on 2026-03-04 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_pars_remove_turnin_on_stock_onstocks_turn_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='par',
        ),
        migrations.AddField(
            model_name='pars',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pars', to='quickstart.persons'),
        ),
        migrations.AlterField(
            model_name='pars',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
