# Generated by Django 6.0.2 on 2026-03-04 15:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_remove_persons_par_pars_person_alter_pars_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnin',
            name='basemodel_ptr',
        ),
        migrations.AddField(
            model_name='guns',
            name='disposition',
            field=models.CharField(blank=True, choices=[('ON_STOCK', 'On Stock'), ('ISSUED', 'Issued'), ('FOR_RELEASE', 'For Release')], default='ON_STOCK', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gun',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_person', to='quickstart.guns'),
        ),
        migrations.CreateModel(
            name='GunHistory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('event_type', models.CharField(blank=True, choices=[('ISSUED', 'Issued'), ('TURN_IN', 'Turn In'), ('STATUS_CHANGE', 'Status Change')], max_length=30, null=True)),
                ('disposition', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2026, 3, 4, 23, 33, 42, 189540), null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='gun_history/')),
                ('gun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='quickstart.guns')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gun_history', to='quickstart.persons')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
            bases=('quickstart.basemodel',),
        ),
        migrations.DeleteModel(
            name='OnStocks',
        ),
        migrations.DeleteModel(
            name='TurnIn',
        ),
    ]
