# Generated by Django 6.0.2 on 2026-03-04 16:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_remove_turnin_basemodel_ptr_guns_disposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 4, 16, 40, 40, 838262, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='GunHistoryImage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quickstart.basemodel')),
                ('img', models.FileField(blank=True, null=True, upload_to='person_attachments/')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quickstart.gunhistory')),
            ],
            bases=('quickstart.basemodel',),
        ),
    ]
