# Generated by Django 6.0.2 on 2026-03-04 17:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_alter_gunhistory_date_gunhistoryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 4, 17, 6, 38, 524891, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gun',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_to', to='quickstart.guns'),
        ),
    ]
