# Generated by Django 6.0.2 on 2026-03-11 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_alter_gunhistory_date_alter_persons_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 3, 11, 6, 4, 2, 842749, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
