# Generated by Django 6.0.2 on 2026-04-08 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0019_alter_gunhistory_date_activitylog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guns',
            old_name='faid',
            new_name='property_no',
        ),
        migrations.RenameField(
            model_name='guns',
            old_name='kind',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='guns',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='guns',
            name='model',
        ),
        migrations.RemoveField(
            model_name='guns',
            name='validated',
        ),
        migrations.AddField(
            model_name='guns',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='acquisition_date',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='balance_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='balance_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='cost_of_repair',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='current_depreciated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='on_hand_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='on_hand_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='over_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='over_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='short_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='short_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='guns',
            name='source',
            field=models.CharField(blank=True, choices=[('PROCURED', 'Procured'), ('DONATED_FOUND_AT_STATION', 'Donated Found at Station'), ('LOANED', 'Loaned')], default='PROCURED', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='gunhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 4, 8, 0, 35, 28, 746898, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='status',
            field=models.CharField(blank=True, choices=[('SVC', 'Svc'), ('UNSVC', 'Unsvc'), ('BER', 'BER')], default='SVC', max_length=250, null=True),
        ),
    ]
