# Generated by Django 6.0.2 on 2026-04-12 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0020_rename_faid_guns_property_no_rename_kind_guns_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 4, 12, 14, 47, 43, 157146, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='balance_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='cost_of_repair',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='current_depreciated_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='on_hand_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='over_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='guns',
            name='short_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
