# Generated by Django 6.0.2 on 2026-04-20 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0021_alter_gunhistory_date_alter_guns_acquisition_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guns',
            name='disposition',
            field=models.CharField(blank=True, choices=[('ISSUED', 'Issued'), ('ON_STOCK', 'On Stock')], default='ON_STOCK', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='gunhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 4, 20, 2, 3, 56, 924918, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
