# Generated by Django 6.0.2 on 2026-04-23 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0022_guns_disposition_alter_gunhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guns',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='gunhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2026, 4, 23, 5, 56, 1, 607518, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
