# Generated by Django 6.0.2 on 2026-03-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('viewer', 'Viewer'), ('super_admin', 'Super Admin')], default='viewer', max_length=20),
        ),
    ]
